/**
 * @file A tree-sitter grammar for the Red programming language
 * @author qtxie <xqtxyz@gmail.com>
 * @license Apache-2.0
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "red",

  extras: ($) => [$.comment, /\s/],
  externals: ($) => [
    $._infix_op,
    $.hexa,
    $.raw_string,
    $.multiline_string,
    $.error_sentinel,
  ],
  word: ($) => $._word,

  //conflicts: ($) => [[$.path, $.set_path]],

  rules: {
    /* General rules */
    source_file: ($) => repeat($._statement_seq),
    _statement_seq: ($) => choice($.include, $._expression),
    include: ($) => seq("#include", $.file),

    /* Comments */
    comment: (_) => /;.*/,

    /* expressions */
    _expression: ($) => choice($._complex_expression, $._simple_expression),
    _simple_expression: ($) => choice($._literal, $.infix),

    infix: ($) =>
      prec.left(
        1,
        seq(
          field("left", $._simple_expression),
          field("operator", $._infix_op),
          field("right", $._simple_expression),
        ),
      ),

    _literal: ($) =>
      choice(
        $._any_string,
        $._any_word,
        $._any_path,
        $.hexa,
        $.escaped_value,
        $.boolean,
        $.number,
        $.pair,
        $.tuple,
        $.char,
        $.file,
        $.issue,
        $.binary,
        $.map,
        $.refinement,
        $.tag,
        $.ref,
        $.email,
        $.point,
        $.money,
        $.time,
        $.date,
      ),

    boolean: (_) => choice("true", "false"),

    number: (_) => {
      const separator = "'";
      const decimal = /[0-9]/;
      const decimalDigits = seq(
        repeat1(decimal),
        repeat(seq(separator, repeat1(decimal))),
      );
      return token(
        choice(
          seq(
            optional(/[-\+]/),
            decimalDigits,
            optional(seq(".", decimalDigits)),
            optional(seq(/[eE]/, optional(seq(optional(/[-\+]/), decimal)))),
            optional("%"),
          ),
          seq(optional(/[-\+]/), choice(/1.#inf/i, /1.#nan/i), optional("%")),
        ),
      );
    },

    pair: (_) => {
      const separator = "'";
      const decimal = /[0-9]/;
      const integer = seq(
        optional(/[-\+]/),
        repeat1(decimal),
        repeat(seq(separator, repeat1(decimal))),
      );
      return token(seq(integer, /[xX]/, integer));
    },

    point: ($) =>
      seq("(", $.number, ",", $.number, optional(seq(",", $.number)), ")"),

    money: (_) =>
      token(
        seq(
          optional(/[-\+]/),
          optional(/[A-Za-z]{3}/),
          "$",
          repeat1(/\d/),
          repeat(seq("'", repeat1(/\d/))),
          optional(seq(".", repeat1(/\d/))),
        ),
      ),

    tuple: (_) => {
      const byte = choice(
        seq("25", /[0-5]/),
        seq("2", /[0-4]/, /\d/),
        seq("1", /\d{2}/),
        seq(optional("0"), /[1-9]/, /\d/),
        seq(optional("0"), optional("0"), /\d/),
        "0",
      );
      const dot_byte = seq(".", byte);
      return token(
        seq(
          byte,
          dot_byte,
          dot_byte,
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
          optional(dot_byte),
        ),
      );
    },

    time: (_) => {
      const decimal_number = token(seq(".", /\d{1,9}/));
      return prec(
        1,
        token(
          seq(
            /\d+:\d+/,
            optional(
              choice(decimal_number, seq(/:\d+/, optional(decimal_number))),
            ),
          ),
        ),
      );
    },

    date: (_) => {
      // Basic components
      const year = /\d{3,4}/;
      const month_num = /\d{1,2}/;
      const day = /\d{1,2}/;
      const decimal_number = token(seq(".", /\d{1,9}/));

      const month_name = token(
        choice(
          /Jan(uary)?/i,
          /Feb(ruary)?/i,
          /Mar(ch)?/i,
          /Apr(il)?/i,
          /May/i,
          /Jun(e)?/i,
          /Jul(y)?/i,
          /Aug(ust)?/i,
          /Sep(t(ember)?)?/i,
          /Oct(ober)?/i,
          /Nov(ember)?/i,
          /Dec(ember)?/i,
        ),
      );
      const month = choice(month_num, month_name);

      const timezone = seq(
        token(
          choice(
            "Z",
            seq(
              choice("+", "-"),
              choice(/\d{4}/, seq(/\d{1,2}/, optional(/:\d{2}/))),
            ),
          ),
        ),
      );

      const _time = prec(
        1,
        token(
          seq(
            /[T\/]\d+:\d+/,
            optional(
              choice(decimal_number, seq(/:\d+/, optional(decimal_number))),
            ),
          ),
        ),
      );
      const time_z = prec(2, seq(_time, optional(timezone)));

      // date
      const ymd_dash = token(seq(year, "-", month, "-", day));
      const ymd_slash = token(seq(year, "/", month, "/", day));
      const dmy_dash = token(seq(day, "-", month, "-", choice(year, day)));
      const dmy_slash = token(seq(day, "/", month, "/", choice(year, day)));
      const yyyymmdd = token(
        seq(
          /\d{8}T/,
          choice(
            seq(/\d{6}/, optional(decimal_number), optional(timezone)),
            /\d{4}Z/,
          ),
        ),
      );
      const yyyywww = token(
        seq(
          year,
          "-",
          choice(seq("W", /\d{2}/, optional(seq("-", /[1-9]/))), /\d{3}/),
        ),
      );

      return choice(
        prec(
          2,
          token(
            seq(
              choice(ymd_dash, ymd_slash, dmy_dash, dmy_slash, yyyywww),
              optional(time_z),
            ),
          ),
        ),
        yyyymmdd,
      );
    },

    char: ($) =>
      seq('#"', choice($.escaped_char, token.immediate(/[^"\^]/)), '"'),

    ref: (_) => /@[^\s\[\]\(\)\{\}@#$;,'"=<>^]*/,
    issue: (_) => /#[^\s\[\]\(\)\{\}@;"<>:]+/,
    refinement: (_) => seq("/", /[^\s\/\\,\[\]\(\)\{\}"#%\$@:;<>]+/),
    email: (_) => {
      const char = /[^\s\[\]\(\)\{\}@;:<"]/;
      return token(seq(repeat1(char), "@", repeat(char)));
    },

    file: ($) => seq("%", choice($.string, $.file_content)),
    file_content: (_) => token.immediate(prec(1, /[^\[\]\(\)\{\}@:;"\n]+/)),

    string: ($) =>
      seq(
        '"',
        repeat(
          choice(
            alias(token.immediate(prec(1, /[^\^\\"\n]+/)), $.string_content),
            $.escaped_char,
          ),
        ),
        '"',
      ),

    escaped_char: (_) =>
      token(
        prec(
          1,
          seq(
            "^",
            choice(
              "/",
              "-",
              "~",
              "^",
              "{",
              "}",
              '"',
              /[a-z@-_]/,
              "(null)",
              "(back)",
              "(tab)",
              "(line)",
              "(page)",
              "(esc)",
              "(del)",
              /\([0-9a-fA-F]{1,6}\)/,
            ),
          ),
        ),
      ),

    escaped_value: (_) => seq("#(", /[A-Za-z\-!]{3,20}/, ")"),

    _word: (_) =>
      /[^\p{White_Space}\d'\/\\,\[\]\(\)\{\}"#%\$@:;][^\p{White_Space}\/\\,\[\]\(\)\{\}"#%\$@:;]*/u,
    word: ($) => choice($._word, /\/+/, $._builtin),
    lit_word: ($) => seq("'", $.word),
    get_word: ($) => seq(":", $.word),
    set_word: ($) =>
      choice(
        /[^\s\d'\/\\,\[\]\(\)\{\}"#%\$@:;!][^\s\/\\,\[\]\(\)\{\}"#%\$@:;!]*:/,
        /\/+:/,
      ),

    type_word: ($) =>
      /[^\s\d'\/\\,\[\]\(\)\{\}"#%\$@:;!][^\s\/\\,\[\]\(\)\{\}"#%\$@:;!]*!/,
    _any_word: ($) => choice($.word, $.lit_word, $.get_word, $.set_word),
    _any_path: ($) => choice($.path, $.lit_path, $.get_path, $.set_path),
    _any_string: ($) => choice($.string, $.multiline_string, $.raw_string),

    _path_element: ($) =>
      choice(
        $.path,
        $.boolean,
        $.number,
        $.pair,
        $.tuple,
        $.char,
        $.file,
        $.string,
        $.issue,
        $.binary,
        $.map,
        $.word,
        $.lit_word,
        $.get_word,
        $.tag,
        $.ref,
      ),
    _path_part: ($) => seq("/", $._path_element),
    path: ($) => prec(1, seq($.word, $._path_part)),
    lit_path: ($) => prec(1, seq("'", $.word, $._path_part)),
    get_path: ($) => prec(1, seq(":", $.word, $._path_part)),
    set_path: ($) => prec(2, seq($.word, $._path_part, ":")),

    _binary_base_2: ($) => seq("2#{", repeat(/(?:[01]\s*){8}/), "}"),
    _binary_base_16: ($) =>
      seq(optional("16"), "#{", repeat(/[0-9a-fA-F]{2}/), "}"),
    _binary_base_64: ($) =>
      seq("64#{", repeat(/[A-Za-z0-9\+\/]/), optional("="), optional("="), "}"),
    binary: ($) =>
      choice($._binary_base_2, $._binary_base_16, $._binary_base_64),

    map: ($) => seq("#[", repeat(seq($._literal, $._literal)), "]"),
    tag: (_) =>
      token(
        prec(
          2,
          seq(
            /<[^\s\[\]\(\)\{\};"<>=]/,
            repeat(choice(/".*"/, /'.*'/, /[^>]/)),
            ">",
          ),
        ),
      ),

    _complex_expression: ($) =>
      choice(
        $.paren,
        $.block,
        $.while,
        $.loop,
        $.function,
        $.routine,
        $.context,
        $.object,
      ),

    block: ($) => seq("[", repeat($._expression), "]"),
    paren: ($) => seq("(", repeat($._simple_expression), ")"),

    while: ($) => seq(choice("while", "While", "WHILE"), $.block, $.block),

    loop: ($) =>
      seq(choice("loop", "LOOP", "Loop"), $._simple_expression, $.block),

    type_block: ($) => seq("[", repeat1($.type_word), "]"),
    func_return: ($) => seq("return:", $.type_block, optional($._any_string)),
    func_param: ($) =>
      seq(choice($.word, $.lit_word, $.get_word), optional($.type_block)),
    func_local: ($) =>
      seq(
        "/local",
        repeat(choice(seq($.word, optional($.type_block)), $._any_string)),
      ),
    func_spec: ($) =>
      seq(
        "[",
        optional(field("attribute", $.block)),
        repeat(choice($.func_param, $.refinement, $._any_string)),
        optional($.func_return),
        optional($.func_local),
        "]",
      ),

    function: ($) =>
      seq(
        field("name", choice($.set_word, $.set_path)),
        field(
          "func",
          choice("func", "Func", "FUNC", "function", "Function", "FUNCTION"),
        ),
        $.func_spec,
        $.block,
      ),
    routine: ($) =>
      seq(
        field("name", choice($.set_word, $.set_path)),
        "routine",
        $.func_spec,
        $.block,
      ),
    context: ($) =>
      seq(
        field("name", choice($.set_word, $.set_path)),
        field("ctx", choice("context", "Context", "CONTEXT")),
        $.block,
      ),
    object: ($) =>
      seq(
        field("name", choice($.set_word, $.set_path)),
        field("obj", choice("object", "Object", "OBJECT")),
        $.block,
      ),

    _builtin: (_) =>
      choice(
        "about",
        "ajoin",
        "alert",
        "also",
        "alter",
        "any-object?",
        "any-path?",
        "append",
        "apply",
        "array",
        "as-pair",
        "ascii?",
        "ask",
        "assert",
        "attempt",
        "bb",
        "body-of",
        "brightness?",
        "build-attach-body",
        "build-markup",
        "build-tag",
        "cause-error",
        "cd",
        "center-face",
        "change-dir",
        "charset",
        "choose",
        "clean-path",
        "clear-face",
        "clear-fields",
        "closure",
        "closure?",
        "collect",
        "collect-words",
        "component?",
        "confine",
        "confirm",
        "cvs-date",
        "cvs-version",
        "dbug",
        "decode-cgi",
        "decode-url",
        "default",
        "deflag-face",
        "delete",
        "delete-dir",
        "deline",
        "delta-time",
        "desktop",
        "dir?",
        "dirize",
        "dispatch",
        "do-boot",
        "do-events",
        "do-face",
        "do-face-alt",
        "do-thru",
        "does",
        "dt",
        "dump-face",
        "dump-obj",
        "dump-pane",
        "echo",
        "edge-size?",
        "editor",
        "emailer",
        "enline",
        "exists-thru?",
        "exists?",
        "extract",
        "find-key-face",
        "find-window",
        "first+",
        "flag-face",
        "flag-face?",
        "flash",
        "focus",
        "foo",
        "foo10",
        "foo9",
        "for",
        "forall",
        "forever",
        "forskip",
        "found?",
        "funct",
        "get-face",
        "get-net-info",
        "get-path?",
        "get-style",
        "has",
        "help",
        "hide-popup",
        "hilight-all",
        "hilight-text",
        "import-email",
        "in-dir",
        "in-window?",
        "info?",
        "inform",
        "input",
        "insert-event-func",
        "inside?",
        "install",
        "invalid-utf?",
        "join",
        "last?",
        "latin1?",
        "launch-thru",
        "layout",
        "license",
        "link-app?",
        "link-relative-path",
        "link?",
        "list-dir",
        "load-image",
        "load-stock",
        "load-stock-block",
        "load-thru",
        "ls",
        "make-dir",
        "make-face",
        "map-each",
        "mod",
        "modified?",
        "modulo",
        "more",
        "move",
        "net-error",
        "notify",
        "offset?",
        "open-events",
        "outside?",
        "overlap?",
        "parse-email-addrs",
        "parse-header",
        "parse-header-date",
        "parse-xml",
        "path-thru",
        "probe",
        "protect-system",
        "pwd",
        "quote",
        "read-cgi",
        "read-net",
        "read-thru",
        "reflect",
        "reform",
        "rejoin",
        "remold",
        "remove-event-func",
        "rename",
        "repend",
        "replace",
        "request",
        "request-color",
        "request-date",
        "request-dir",
        "request-download",
        "request-file",
        "request-list",
        "request-pass",
        "request-text",
        "resend",
        "reset-face",
        "resize-face",
        "resolve",
        "rm",
        "round",
        "save-user",
        "scalar?",
        "screen-offset?",
        "scroll-drag",
        "scroll-face",
        "scroll-para",
        "send",
        "set-face",
        "set-font",
        "set-net",
        "set-para",
        "set-style",
        "set-user-name",
        "show-popup",
        "sign?",
        "size?",
        "source",
        "span?",
        "spec-of",
        "speed?",
        "split-path",
        "stylize",
        "suffix?",
        "swap",
        "take",
        "throw-error",
        "throw-on-error",
        "title-of",
        "to-binary",
        "to-bitset",
        "to-block",
        "to-char",
        "to-closure",
        "to-datatype",
        "to-date",
        "to-decimal",
        "to-email",
        "to-error",
        "to-file",
        "to-function",
        "to-get-path",
        "to-get-word",
        "to-hash",
        "to-idate",
        "to-image",
        "to-integer",
        "to-issue",
        "to-itime",
        "to-library",
        "to-list",
        "to-lit-path",
        "to-lit-word",
        "to-logic",
        "to-map",
        "to-money",
        "to-none",
        "to-pair",
        "to-paren",
        "to-path",
        "to-port",
        "to-refinement",
        "to-relative-file",
        "to-set-path",
        "to-set-word",
        "to-string",
        "to-tag",
        "to-time",
        "to-tuple",
        "to-typeset",
        "to-url",
        "to-word",
        "true?",
        "types-of",
        "typeset?",
        "undirize",
        "unfocus",
        "uninstall",
        "unlight-text",
        "unview",
        "upgrade",
        "Usage",
        "utf?",
        "values-of",
        "vbug",
        "view",
        "viewed?",
        "viewtop",
        "what",
        "what-dir",
        "win-offset?",
        "within?",
        "words-of",
        "write-user",
        "access-os",
        "alias",
        "all",
        "any",
        "arccosine",
        "arcsine",
        "arctangent",
        "as",
        "AS",
        "as-binary",
        "as-string",
        "bind",
        "bind?",
        "bound?",
        "break",
        "browse",
        "call",
        "caret-to-offset",
        "case",
        "catch",
        "checksum",
        "close",
        "comment",
        "compose",
        "compress",
        "continue",
        "connected?",
        "construct",
        "cosine",
        "create-link",
        "crypt-strength?",
        "debase",
        "declare",
        "decloak",
        "decompress",
        "dehex",
        "detab",
        "dh-compute-key",
        "dh-generate-key",
        "dh-make-key",
        "difference",
        "disarm",
        "do",
        "do-browser",
        "draw",
        "dsa-generate-key",
        "dsa-make-key",
        "dsa-make-signature",
        "dsa-verify-signature",
        "either",
        "else",
        "enbase",
        "encloak",
        "entab",
        "exclude",
        "exit",
        "exp",
        "foreach",
        "form",
        "free",
        "get",
        "get-env",
        "get-modes",
        "halt",
        "hide",
        "hsv-to-rgb",
        "if",
        "in",
        "input?",
        "intersect",
        "launch",
        "list-env",
        "load",
        "local-request-file",
        "log-10",
        "log-2",
        "log-e",
        "lowercase",
        "maximum-of",
        "minimum-of",
        "mold",
        "native",
        "new-line",
        "new-line?",
        "not",
        "now",
        "offset-to-caret",
        "open",
        "parse",
        "prin",
        "print",
        "protect",
        "q",
        "query",
        "quit",
        "quit-return",
        "read",
        "read-io",
        "recycle",
        "reduce",
        "remove-each",
        "repeat",
        "reverse",
        "rgb-to-hsv",
        "rsa-encrypt",
        "rsa-generate-key",
        "rsa-make-key",
        "run",
        "save",
        "script?",
        "secure",
        "set",
        "set-env",
        "set-modes",
        "shift",
        "show",
        "sine",
        "size-text",
        "square-root",
        "stats",
        "switch",
        "tangent",
        "textinfo",
        "throw",
        "to-hex",
        "to-local-file",
        "to-rebol-file",
        "trace",
        "try",
        "type?",
        "unbind",
        "union",
        "unique",
        "unless",
        "unprotect",
        "unset",
        "until",
        "update",
        "uppercase",
        "use",
        "value?",
        "wait",
        "with",
        "write",
        "write-io",
        "abs",
        "absolute",
        "action?",
        "add",
        "and~",
        "any-block?",
        "any-function?",
        "any-series?",
        "any-string?",
        "any-type?",
        "any-word?",
        "at",
        "back",
        "binary?",
        "bitset?",
        "block?",
        "change",
        "char?",
        "clear",
        "complement",
        "copy",
        "copy*",
        "cp",
        "datatype?",
        "date?",
        "decimal?",
        "divide",
        "eighth",
        "email?",
        "empty?",
        "equal?",
        "error?",
        "even?",
        "event?",
        "fifth",
        "file?",
        "find",
        "first",
        "fourth",
        "function?",
        "get-word?",
        "greater-or-equal?",
        "greater?",
        "hash?",
        "head",
        "head?",
        "image?",
        "index?",
        "insert",
        "integer?",
        "issue?",
        "last",
        "length?",
        "lesser-or-equal?",
        "lesser?",
        "library?",
        "list?",
        "lit-path?",
        "lit-word?",
        "logic?",
        "make",
        "map?",
        "max",
        "maximum",
        "min",
        "minimum",
        "money?",
        "multiply",
        "native?",
        "negate",
        "negative?",
        "next",
        "ninth",
        "none?",
        "not-equal?",
        "number?",
        "object?",
        "odd?",
        "op?",
        "or~",
        "pair?",
        "paren?",
        "path",
        "path?",
        "pick",
        "poke",
        "port?",
        "positive?",
        "power",
        "random",
        "refinement?",
        "remainder",
        "remove",
        "routine?",
        "same?",
        "second",
        "select",
        "series?",
        "set-path?",
        "set-word?",
        "seventh",
        "sixth",
        "skip",
        "sort",
        "strict-equal?",
        "strict-not-equal?",
        "string?",
        "struct?",
        "subtract",
        "tag?",
        "tail",
        "tail?",
        "tenth",
        "third",
        "time?",
        "to",
        "trim",
        "tuple?",
        "unset?",
        "url?",
        "word?",
        "xor~",
        "zero?",
        "backslash",
        "backspace",
        "bs",
        "cr",
        "escape",
        "lf",
        "newline",
        "newpage",
        "null",
        "slash",
        "tab",
        "sp",
        "space",
        "crlf",
        "dot",
        "yes",
        "no",
        "on",
        "off",
        "return",
        "CR",
        "LF",
        "CRLF",
        "BS",
        "SP",
        "ON",
        "OFF",
      ),
  },
});
