/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_word = 1,
  sym_comment = 2,
  anon_sym_POUNDinclude = 3,
  anon_sym_PERCENT = 4,
  sym_file_content = 5,
  anon_sym_DQUOTE = 6,
  aux_sym_string_token1 = 7,
  sym_escaped_char = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  sym_number = 11,
  sym_pair = 12,
  sym_tuple = 13,
  anon_sym_POUND_DQUOTE = 14,
  aux_sym_char_token1 = 15,
  anon_sym_SQUOTE = 16,
  anon_sym_COLON = 17,
  anon_sym_SLASH = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  anon_sym_while = 21,
  anon_sym_loop = 22,
  sym__infix_op = 23,
  sym_error_sentinel = 24,
  sym_source_file = 25,
  sym__statement_seq = 26,
  sym_include = 27,
  sym_file = 28,
  sym_string = 29,
  sym__expression = 30,
  sym__simple_expression = 31,
  sym__path_element = 32,
  sym_binary_expression = 33,
  sym__literal = 34,
  sym_boolean = 35,
  sym_char = 36,
  sym_lit_word = 37,
  sym_get_word = 38,
  sym_set_word = 39,
  sym_path = 40,
  sym_lit_path = 41,
  sym_get_path = 42,
  sym_set_path = 43,
  sym__complex_expression = 44,
  sym_block = 45,
  sym_while = 46,
  sym_loop = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_string_repeat1 = 49,
  aux_sym_path_repeat1 = 50,
  aux_sym_block_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "word",
  [sym_comment] = "comment",
  [anon_sym_POUNDinclude] = "#include",
  [anon_sym_PERCENT] = "%",
  [sym_file_content] = "file_content",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_content",
  [sym_escaped_char] = "escaped_char",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [sym_pair] = "pair",
  [sym_tuple] = "tuple",
  [anon_sym_POUND_DQUOTE] = "#\"",
  [aux_sym_char_token1] = "char_token1",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_while] = "while",
  [anon_sym_loop] = "loop",
  [sym__infix_op] = "_infix_op",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym__statement_seq] = "_statement_seq",
  [sym_include] = "include",
  [sym_file] = "file",
  [sym_string] = "string",
  [sym__expression] = "_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym__path_element] = "_path_element",
  [sym_binary_expression] = "binary_expression",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym_char] = "char",
  [sym_lit_word] = "lit_word",
  [sym_get_word] = "get_word",
  [sym_set_word] = "set_word",
  [sym_path] = "path",
  [sym_lit_path] = "lit_path",
  [sym_get_path] = "get_path",
  [sym_set_path] = "set_path",
  [sym__complex_expression] = "_complex_expression",
  [sym_block] = "block",
  [sym_while] = "while",
  [sym_loop] = "loop",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [sym_comment] = sym_comment,
  [anon_sym_POUNDinclude] = anon_sym_POUNDinclude,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_file_content] = sym_file_content,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escaped_char] = sym_escaped_char,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [sym_pair] = sym_pair,
  [sym_tuple] = sym_tuple,
  [anon_sym_POUND_DQUOTE] = anon_sym_POUND_DQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_loop] = anon_sym_loop,
  [sym__infix_op] = sym__infix_op,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym__statement_seq] = sym__statement_seq,
  [sym_include] = sym_include,
  [sym_file] = sym_file,
  [sym_string] = sym_string,
  [sym__expression] = sym__expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym__path_element] = sym__path_element,
  [sym_binary_expression] = sym_binary_expression,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym_char] = sym_char,
  [sym_lit_word] = sym_lit_word,
  [sym_get_word] = sym_get_word,
  [sym_set_word] = sym_set_word,
  [sym_path] = sym_path,
  [sym_lit_path] = sym_lit_path,
  [sym_get_path] = sym_get_path,
  [sym_set_path] = sym_set_path,
  [sym__complex_expression] = sym__complex_expression,
  [sym_block] = sym_block,
  [sym_while] = sym_while,
  [sym_loop] = sym_loop,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_file_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [sym__infix_op] = {
    .visible = false,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_seq] = {
    .visible = false,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__path_element] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_lit_word] = {
    .visible = true,
    .named = true,
  },
  [sym_get_word] = {
    .visible = true,
    .named = true,
  },
  [sym_set_word] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_lit_path] = {
    .visible = true,
    .named = true,
  },
  [sym_get_path] = {
    .visible = true,
    .named = true,
  },
  [sym_set_path] = {
    .visible = true,
    .named = true,
  },
  [sym__complex_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_loop] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 17,
  [35] = 18,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 36,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
};

static const TSCharacterRange sym_file_content_character_set_1[] = {
  {0, '\t'}, {0x0b, '!'}, {'#', '\''}, {'*', '9'}, {'<', '?'}, {'A', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static const TSCharacterRange sym_escaped_char_character_set_1[] = {
  {'"', '"'}, {'(', '('}, {'-', '-'}, {'/', '/'}, {'A', 'F'}, {'^', '^'}, {'a', 'f'}, {'{', '{'},
  {'}', '~'},
};

static const TSCharacterRange sym_word_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'&', '&'}, {'*', '+'}, {'-', '.'}, {'<', '?'}, {'A', 'Z'},
  {'^', 'z'}, {'|', '|'}, {'~', 0x84}, {0x86, 0x9f}, {0xa1, 0x167f}, {0x1681, 0x1fff}, {0x200b, 0x2027}, {0x202a, 0x202e},
  {0x2030, 0x205e}, {0x2060, 0x2fff}, {0x3001, 0x10ffff},
};

static const TSCharacterRange sym_word_character_set_2[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'&', '\''}, {'*', '+'}, {'-', '.'}, {'0', '9'}, {'<', '?'},
  {'A', 'Z'}, {'^', 'z'}, {'|', '|'}, {'~', 0x84}, {0x86, 0x9f}, {0xa1, 0x167f}, {0x1681, 0x1fff}, {0x200b, 0x2027},
  {0x202a, 0x202e}, {0x2030, 0x205e}, {0x2060, 0x2fff}, {0x3001, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(64);
      ADVANCE_MAP(
        '"', 70,
        '#', 5,
        '%', 67,
        '\'', 176,
        '/', 178,
        '0', 79,
        '1', 85,
        '2', 80,
        ':', 177,
        ';', 65,
        '[', 179,
        ']', 180,
        '+', 169,
        '-', 169,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == ';') ADVANCE(72);
      if (lookahead == '^') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == ';') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if ((!eof && set_contains(sym_file_content_character_set_1, 10, lookahead))) ADVANCE(69);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == ';') ADVANCE(65);
      if (lookahead == '^') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == ';') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(161);
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '0') ADVANCE(89);
      if (lookahead == '1') ADVANCE(94);
      if (lookahead == '2') ADVANCE(90);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 10:
      if (lookahead == '(') ADVANCE(38);
      if (set_contains(sym_escaped_char_character_set_1, 9, lookahead)) ADVANCE(73);
      END_STATE();
    case 11:
      if (lookahead == ')') ADVANCE(73);
      END_STATE();
    case 12:
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == 'a') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == 'c') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == 'k') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == 'l') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == 's') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == ')') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 19:
      if (lookahead == ')') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == ')') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == ')') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == ')') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == '0') ADVANCE(89);
      if (lookahead == '1') ADVANCE(94);
      if (lookahead == '2') ADVANCE(90);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 24:
      if (lookahead == '0') ADVANCE(151);
      if (lookahead == '1') ADVANCE(155);
      if (lookahead == '2') ADVANCE(152);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 25:
      if (lookahead == '0') ADVANCE(156);
      if (lookahead == '1') ADVANCE(160);
      if (lookahead == '2') ADVANCE(157);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(159);
      END_STATE();
    case 26:
      if (lookahead == '0') ADVANCE(103);
      if (lookahead == '1') ADVANCE(106);
      if (lookahead == '2') ADVANCE(104);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(107);
      END_STATE();
    case 27:
      if (lookahead == '0') ADVANCE(109);
      if (lookahead == '1') ADVANCE(112);
      if (lookahead == '2') ADVANCE(110);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 28:
      if (lookahead == '0') ADVANCE(115);
      if (lookahead == '1') ADVANCE(118);
      if (lookahead == '2') ADVANCE(116);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 29:
      if (lookahead == '0') ADVANCE(121);
      if (lookahead == '1') ADVANCE(124);
      if (lookahead == '2') ADVANCE(122);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 30:
      if (lookahead == '0') ADVANCE(127);
      if (lookahead == '1') ADVANCE(130);
      if (lookahead == '2') ADVANCE(128);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 31:
      if (lookahead == '0') ADVANCE(133);
      if (lookahead == '1') ADVANCE(136);
      if (lookahead == '2') ADVANCE(134);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 32:
      if (lookahead == '0') ADVANCE(139);
      if (lookahead == '1') ADVANCE(142);
      if (lookahead == '2') ADVANCE(140);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 33:
      if (lookahead == '0') ADVANCE(145);
      if (lookahead == '1') ADVANCE(148);
      if (lookahead == '2') ADVANCE(146);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 34:
      if (lookahead == ';') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if ((!eof && set_contains(sym_word_character_set_1, 19, lookahead))) ADVANCE(175);
      END_STATE();
    case 35:
      if (lookahead == ';') ADVANCE(164);
      if (lookahead == '^') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(162);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'b') ADVANCE(12);
      if (lookahead == 'd') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(46);
      if (lookahead == 'n') ADVANCE(53);
      if (lookahead == 'p') ADVANCE(36);
      if (lookahead == 't') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 39:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 42:
      if (lookahead == 'd') ADVANCE(43);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 45:
      if (lookahead == 'g') ADVANCE(44);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 54:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 55:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 56:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(74);
      END_STATE();
    case 57:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(59);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 58:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 59:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUNDinclude);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_file_content);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if ((!eof && set_contains(sym_file_content_character_set_1, 10, lookahead))) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_file_content);
      if ((!eof && set_contains(sym_file_content_character_set_1, 10, lookahead))) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ';') ADVANCE(72);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_escaped_char);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '\'') ADVANCE(171);
      if (lookahead == '.') ADVANCE(172);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(97);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '0') ADVANCE(83);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '5') ADVANCE(81);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(77);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(166);
      if (lookahead == '.') ADVANCE(167);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(78);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          ('"' <= lookahead && lookahead <= '%') ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          ('/' <= lookahead && lookahead <= ';') ||
          lookahead == '@' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}' ||
          lookahead == 0x85 ||
          lookahead == 0xa0 ||
          lookahead == 0x1680 ||
          (0x2000 <= lookahead && lookahead <= 0x200a) ||
          lookahead == 0x2028 ||
          lookahead == 0x2029 ||
          lookahead == 0x202f ||
          lookahead == 0x205f ||
          lookahead == 0x3000) ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(168);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(171);
      if (lookahead == '.') ADVANCE(172);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(97);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(172);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == '0') ADVANCE(93);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == '5') ADVANCE(91);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_number);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_pair);
      if (lookahead == '\'') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_pair);
      if (lookahead == '\'') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_tuple);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(25);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == '0') ADVANCE(107);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(107);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == '5') ADVANCE(105);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(102);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(102);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(26);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '0') ADVANCE(113);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '5') ADVANCE(111);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(113);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(108);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(27);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '0') ADVANCE(119);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '5') ADVANCE(117);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(119);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(114);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(28);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '0') ADVANCE(125);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '5') ADVANCE(123);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(120);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(29);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '0') ADVANCE(131);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '5') ADVANCE(129);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(131);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(126);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '0') ADVANCE(137);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '5') ADVANCE(135);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(137);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(132);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(31);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '0') ADVANCE(143);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '5') ADVANCE(141);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(143);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(138);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(32);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == '0') ADVANCE(149);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == '5') ADVANCE(147);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(149);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(144);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(33);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '0') ADVANCE(154);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '5') ADVANCE(153);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(154);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(150);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(150);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '0') ADVANCE(159);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(159);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_tuple);
      if (lookahead == '5') ADVANCE(158);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(159);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_tuple);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(101);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_tuple);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_tuple);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(159);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_POUND_DQUOTE);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == '^') ADVANCE(10);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '#') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '#') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '#') ADVANCE(57);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '1') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_word);
      if ((!eof && set_contains(sym_word_character_set_2, 20, lookahead))) ADVANCE(175);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'l') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == 'w') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 35},
  [47] = {.lex_state = 34},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 34},
  [50] = {.lex_state = 34},
  [51] = {.lex_state = 34},
  [52] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_POUNDinclude] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_pair] = ACTIONS(1),
    [sym_tuple] = ACTIONS(1),
    [anon_sym_POUND_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [sym__infix_op] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(48),
    [sym__statement_seq] = STATE(2),
    [sym_include] = STATE(2),
    [sym_string] = STATE(27),
    [sym__expression] = STATE(2),
    [sym__simple_expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__literal] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_char] = STATE(27),
    [sym_lit_word] = STATE(27),
    [sym_get_word] = STATE(27),
    [sym_set_word] = STATE(27),
    [sym_path] = STATE(27),
    [sym_lit_path] = STATE(27),
    [sym_get_path] = STATE(27),
    [sym_set_path] = STATE(27),
    [sym__complex_expression] = STATE(2),
    [sym_while] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_word] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_POUNDinclude] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_pair] = ACTIONS(15),
    [sym_tuple] = ACTIONS(17),
    [anon_sym_POUND_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_loop] = ACTIONS(27),
  },
  [STATE(2)] = {
    [sym__statement_seq] = STATE(3),
    [sym_include] = STATE(3),
    [sym_string] = STATE(27),
    [sym__expression] = STATE(3),
    [sym__simple_expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__literal] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_char] = STATE(27),
    [sym_lit_word] = STATE(27),
    [sym_get_word] = STATE(27),
    [sym_set_word] = STATE(27),
    [sym_path] = STATE(27),
    [sym_lit_path] = STATE(27),
    [sym_get_path] = STATE(27),
    [sym_set_path] = STATE(27),
    [sym__complex_expression] = STATE(3),
    [sym_while] = STATE(3),
    [sym_loop] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_word] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_POUNDinclude] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_pair] = ACTIONS(15),
    [sym_tuple] = ACTIONS(17),
    [anon_sym_POUND_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_loop] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym__statement_seq] = STATE(3),
    [sym_include] = STATE(3),
    [sym_string] = STATE(27),
    [sym__expression] = STATE(3),
    [sym__simple_expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__literal] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_char] = STATE(27),
    [sym_lit_word] = STATE(27),
    [sym_get_word] = STATE(27),
    [sym_set_word] = STATE(27),
    [sym_path] = STATE(27),
    [sym_lit_path] = STATE(27),
    [sym_get_path] = STATE(27),
    [sym_set_path] = STATE(27),
    [sym__complex_expression] = STATE(3),
    [sym_while] = STATE(3),
    [sym_loop] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_word] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [anon_sym_POUNDinclude] = ACTIONS(36),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(42),
    [anon_sym_false] = ACTIONS(42),
    [sym_number] = ACTIONS(45),
    [sym_pair] = ACTIONS(45),
    [sym_tuple] = ACTIONS(48),
    [anon_sym_POUND_DQUOTE] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(54),
    [anon_sym_COLON] = ACTIONS(57),
    [anon_sym_while] = ACTIONS(60),
    [anon_sym_loop] = ACTIONS(63),
  },
  [STATE(4)] = {
    [sym_string] = STATE(27),
    [sym__expression] = STATE(5),
    [sym__simple_expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__literal] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_char] = STATE(27),
    [sym_lit_word] = STATE(27),
    [sym_get_word] = STATE(27),
    [sym_set_word] = STATE(27),
    [sym_path] = STATE(27),
    [sym_lit_path] = STATE(27),
    [sym_get_path] = STATE(27),
    [sym_set_path] = STATE(27),
    [sym__complex_expression] = STATE(5),
    [sym_while] = STATE(5),
    [sym_loop] = STATE(5),
    [aux_sym_block_repeat1] = STATE(5),
    [sym_word] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_pair] = ACTIONS(15),
    [sym_tuple] = ACTIONS(17),
    [anon_sym_POUND_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(66),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_loop] = ACTIONS(27),
  },
  [STATE(5)] = {
    [sym_string] = STATE(27),
    [sym__expression] = STATE(6),
    [sym__simple_expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__literal] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_char] = STATE(27),
    [sym_lit_word] = STATE(27),
    [sym_get_word] = STATE(27),
    [sym_set_word] = STATE(27),
    [sym_path] = STATE(27),
    [sym_lit_path] = STATE(27),
    [sym_get_path] = STATE(27),
    [sym_set_path] = STATE(27),
    [sym__complex_expression] = STATE(6),
    [sym_while] = STATE(6),
    [sym_loop] = STATE(6),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_word] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_pair] = ACTIONS(15),
    [sym_tuple] = ACTIONS(17),
    [anon_sym_POUND_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(68),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_loop] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym_string] = STATE(27),
    [sym__expression] = STATE(6),
    [sym__simple_expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__literal] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_char] = STATE(27),
    [sym_lit_word] = STATE(27),
    [sym_get_word] = STATE(27),
    [sym_set_word] = STATE(27),
    [sym_path] = STATE(27),
    [sym_lit_path] = STATE(27),
    [sym_get_path] = STATE(27),
    [sym_set_path] = STATE(27),
    [sym__complex_expression] = STATE(6),
    [sym_while] = STATE(6),
    [sym_loop] = STATE(6),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_word] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(79),
    [sym_pair] = ACTIONS(79),
    [sym_tuple] = ACTIONS(82),
    [anon_sym_POUND_DQUOTE] = ACTIONS(85),
    [anon_sym_SQUOTE] = ACTIONS(88),
    [anon_sym_COLON] = ACTIONS(91),
    [anon_sym_RBRACK] = ACTIONS(94),
    [anon_sym_while] = ACTIONS(96),
    [anon_sym_loop] = ACTIONS(99),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_word,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(104), 1,
      sym_tuple,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(102), 2,
      sym_number,
      sym_pair,
    STATE(42), 13,
      sym_string,
      sym__simple_expression,
      sym_binary_expression,
      sym__literal,
      sym_boolean,
      sym_char,
      sym_lit_word,
      sym_get_word,
      sym_set_word,
      sym_path,
      sym_lit_path,
      sym_get_path,
      sym_set_path,
  [45] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_word,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(108), 1,
      sym_tuple,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(106), 2,
      sym_number,
      sym_pair,
    STATE(25), 13,
      sym_string,
      sym__simple_expression,
      sym_binary_expression,
      sym__literal,
      sym_boolean,
      sym_char,
      sym_lit_word,
      sym_get_word,
      sym_set_word,
      sym_path,
      sym_lit_path,
      sym_get_path,
      sym_set_path,
  [90] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      aux_sym_path_repeat1,
    ACTIONS(112), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(110), 9,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [123] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    STATE(15), 1,
      aux_sym_path_repeat1,
    ACTIONS(120), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(118), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [154] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(126), 1,
      anon_sym_COLON,
    STATE(14), 1,
      aux_sym_path_repeat1,
    ACTIONS(124), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(122), 9,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [187] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      aux_sym_path_repeat1,
    ACTIONS(130), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(128), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [218] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_path_repeat1,
    ACTIONS(134), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(132), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [249] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_path_repeat1,
    ACTIONS(138), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(136), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [280] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_path_repeat1,
    ACTIONS(145), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(143), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [311] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(147), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(151), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(155), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [389] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(159), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(136), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [441] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(128), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [467] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(118), 11,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [493] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(165), 1,
      sym_tuple,
    ACTIONS(167), 1,
      anon_sym_SQUOTE,
    ACTIONS(169), 1,
      anon_sym_COLON,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(163), 3,
      sym_number,
      sym_pair,
      sym_word,
    STATE(20), 7,
      sym_string,
      sym__path_element,
      sym__literal,
      sym_boolean,
      sym_char,
      sym_lit_word,
      sym_get_word,
  [530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(171), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [555] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(175), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [580] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(179), 10,
      sym__infix_op,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [605] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym__infix_op,
    ACTIONS(185), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(183), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_RBRACK,
  [631] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(189), 9,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [655] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(193), 9,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [679] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(197), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_RBRACK,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
    ACTIONS(201), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_RBRACK,
  [725] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
    ACTIONS(207), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
  [747] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
    ACTIONS(211), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
  [769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
    ACTIONS(153), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
  [791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDinclude,
      anon_sym_DQUOTE,
      sym_tuple,
      anon_sym_POUND_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COLON,
    ACTIONS(157), 7,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      sym_pair,
      sym_word,
      anon_sym_while,
      anon_sym_loop,
  [813] = 5,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
    ACTIONS(217), 1,
      aux_sym_string_token1,
    ACTIONS(219), 1,
      sym_escaped_char,
    STATE(37), 1,
      aux_sym_string_repeat1,
  [829] = 5,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_DQUOTE,
    ACTIONS(223), 1,
      aux_sym_string_token1,
    ACTIONS(225), 1,
      sym_escaped_char,
    STATE(38), 1,
      aux_sym_string_repeat1,
  [845] = 5,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    ACTIONS(229), 1,
      aux_sym_string_token1,
    ACTIONS(232), 1,
      sym_escaped_char,
    STATE(38), 1,
      aux_sym_string_repeat1,
  [861] = 5,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    ACTIONS(237), 1,
      aux_sym_string_token1,
    ACTIONS(239), 1,
      sym_escaped_char,
    STATE(40), 1,
      aux_sym_string_repeat1,
  [877] = 5,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(223), 1,
      aux_sym_string_token1,
    ACTIONS(225), 1,
      sym_escaped_char,
    ACTIONS(241), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_string_repeat1,
  [893] = 4,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_file_content,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      sym_string,
  [906] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym__infix_op,
    ACTIONS(247), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_block,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_PERCENT,
    STATE(33), 1,
      sym_file,
  [929] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LBRACK,
    STATE(30), 1,
      sym_block,
  [939] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LBRACK,
    STATE(44), 1,
      sym_block,
  [949] = 2,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(251), 2,
      sym_escaped_char,
      aux_sym_char_token1,
  [957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_word,
  [964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
  [971] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_word,
  [978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_word,
  [985] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_word,
  [992] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 90,
  [SMALL_STATE(10)] = 123,
  [SMALL_STATE(11)] = 154,
  [SMALL_STATE(12)] = 187,
  [SMALL_STATE(13)] = 218,
  [SMALL_STATE(14)] = 249,
  [SMALL_STATE(15)] = 280,
  [SMALL_STATE(16)] = 311,
  [SMALL_STATE(17)] = 337,
  [SMALL_STATE(18)] = 363,
  [SMALL_STATE(19)] = 389,
  [SMALL_STATE(20)] = 415,
  [SMALL_STATE(21)] = 441,
  [SMALL_STATE(22)] = 467,
  [SMALL_STATE(23)] = 493,
  [SMALL_STATE(24)] = 530,
  [SMALL_STATE(25)] = 555,
  [SMALL_STATE(26)] = 580,
  [SMALL_STATE(27)] = 605,
  [SMALL_STATE(28)] = 631,
  [SMALL_STATE(29)] = 655,
  [SMALL_STATE(30)] = 679,
  [SMALL_STATE(31)] = 702,
  [SMALL_STATE(32)] = 725,
  [SMALL_STATE(33)] = 747,
  [SMALL_STATE(34)] = 769,
  [SMALL_STATE(35)] = 791,
  [SMALL_STATE(36)] = 813,
  [SMALL_STATE(37)] = 829,
  [SMALL_STATE(38)] = 845,
  [SMALL_STATE(39)] = 861,
  [SMALL_STATE(40)] = 877,
  [SMALL_STATE(41)] = 893,
  [SMALL_STATE(42)] = 906,
  [SMALL_STATE(43)] = 919,
  [SMALL_STATE(44)] = 929,
  [SMALL_STATE(45)] = 939,
  [SMALL_STATE(46)] = 949,
  [SMALL_STATE(47)] = 957,
  [SMALL_STATE(48)] = 964,
  [SMALL_STATE(49)] = 971,
  [SMALL_STATE(50)] = 978,
  [SMALL_STATE(51)] = 985,
  [SMALL_STATE(52)] = 992,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lit_word, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lit_word, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get_word, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get_word, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get_path, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get_path, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lit_path, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lit_path, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_word, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_word, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_path, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_path, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [232] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [255] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__infix_op = 0,
  ts_external_token_error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__infix_op] = sym__infix_op,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__infix_op] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__infix_op] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_red_external_scanner_create(void);
void tree_sitter_red_external_scanner_destroy(void *);
bool tree_sitter_red_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_red_external_scanner_serialize(void *, char *);
void tree_sitter_red_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_red(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_word,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_red_external_scanner_create,
      tree_sitter_red_external_scanner_destroy,
      tree_sitter_red_external_scanner_scan,
      tree_sitter_red_external_scanner_serialize,
      tree_sitter_red_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "red",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
